spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.194.188.93:3306/quartz?autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: bmsoft
  quartz:
    auto-startup: true
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: ${spring.application.name}
            instanceId: AUTO
            instanceIdGenerator:
              class: org.example.quartz.parent.config.QuartzInstanceIdGenerator
            skipUpdateCheck: true
            batchTriggerAcquisitionMaxCount: 1
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 3
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: false
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            misfireThreshold: 20000
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 7500
            dataSource: quartzDataSource
            acquireTriggersWithinLock: true
          dataSource:
            quartzDataSource:
              driver: com.mysql.cj.jdbc.Driver
              provider: hikaricp
              URL: jdbc:mysql://10.194.188.93:3306/quartz?autoReconnect=true&serverTimezone=GMT%2B8
              user: root
              password: bmsoft
              maxConnections: 10
          plugin:
            shutdownHook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: TRUE